name: Update Docker Tag

on:
  push:
    branches:
      - main

jobs:
  build-and-rename-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.17

      - name: Install dependencies
        run: |
          pip install requests

      - name: Execute the Python script
        env:    
          TAG_TO_REPLACE: ${{ secrets.TAG_TO_REPLACE }} 
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          python ./changetag.py
              - name: Deploy to Local Machine

        run: |
          ssh darbi@darbi-aspiree5572g "kubectl apply -f /home/darbi/Vid√©os/stage/kubernetis/front.yml"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        shell: bash
